<?php
return array(
    'shop_advertum_visits' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'uid' => array('varchar', 11, 'null' => 0),
        'old_uid' => array('varchar', 11),
        'create_datetime' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'uid' => 'uid',
        ),
    ),
    'shop_advertum_orders' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'uid' => array('varchar', 32, 'null' => 0),
        'order_id' => array('int', 11, 'unsigned' => 1),
        'status' => array('varchar', 11, 'null' => 0),
        'create_price' => array('decimal', "15,4"),
        'create_datetime' => array('datetime', 'null' => 0),
        'paid_price' => array('decimal', "15,4"),
        'paid_datetime' => array('datetime'),
        'canceled_price' => array('decimal', "15,4"),
        'canceled_datetime' => array('datetime'),
        'advertum_user_pushed_datetime' => array('datetime'),
        'advertum_user_accrued_datetime' => array('datetime'),
        'shop_invoiced_datetime' => array('datetime'),
        'advertum_paid_datetime' => array('datetime'),
        'cashback_percentage' => array('decimal', "4,2"),
        'cashback' => array('decimal', "15,4"),
        'currency' => array('char', 3, 'null' => 0),
        'shipping' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'discount' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'contact_id' => array('int', 11),
        'items' => array('text'),
        'props' => array('json'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'uid' => 'uid',
            'uid_order_id' => array('uid', 'order_id'),
            'status' => 'status',
        ),
    ),
);